-- SMS "inclus in abonament": trimise prin contul SMSLink al platformei, in limita pachetului lunar al statiei.
-- sms_plan = cate SMS pe luna are statia (0 / null = niciun pachet), setat de admin.
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS sms_plan integer;

-- Cate SMS (parti taxate) a folosit fiecare statie din pachet, pe luna ("2026-10")
CREATE TABLE sms_usage (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    period character varying(7) NOT NULL,
    sent integer NOT NULL,
    CONSTRAINT uk_sms_usage_user_period UNIQUE (user_id, period)
);
