-- Termenele statiei (D1): autorizatia RAR, verificarile metrologice ale echipamentelor, atestatele inspectorilor
CREATE TABLE station_deadlines (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    kind character varying(30) NOT NULL,
    title character varying(120),
    due_date date NOT NULL,
    notes character varying(300),
    created_at timestamp(6) without time zone NOT NULL
);
CREATE INDEX idx_station_deadlines_user_due ON station_deadlines (user_id, due_date);
