-- Facturare prin Oblio (D3): contul Oblio al statiei, adresa firmelor (pentru e-Factura) si facturile emise
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS oblio_email character varying(200);
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS oblio_secret character varying(200);
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS oblio_cif character varying(30);
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS oblio_series character varying(30);
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS oblio_vat_name character varying(60);
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS oblio_vat_percent double precision;
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS oblio_vat_included boolean;
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS oblio_einvoice boolean;
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS oblio_due_days integer;

ALTER TABLE fleets ADD COLUMN IF NOT EXISTS address character varying(200);
ALTER TABLE fleets ADD COLUMN IF NOT EXISTS city character varying(80);
ALTER TABLE fleets ADD COLUMN IF NOT EXISTS county character varying(80);

-- O factura pe flota si luna (centralizatorul) sau pe un ITP (persoana fizica)
CREATE TABLE invoices (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    fleet_id bigint,
    period character varying(7),
    itp_record_id bigint,
    client_name character varying(200),
    series_name character varying(30) NOT NULL,
    number character varying(30) NOT NULL,
    link character varying(500),
    total double precision NOT NULL,
    einvoice_status character varying(200),
    created_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT uk_invoices_fleet_period UNIQUE (fleet_id, period),
    CONSTRAINT uk_invoices_itp UNIQUE (itp_record_id)
);
CREATE INDEX idx_invoices_user ON invoices (user_id, created_at);
