-- Abonamente (E1): pachetul statiei (FREE / PRO / PREMIUM; null = cont vechi, Premium fara expirare),
-- pana cand e platit (inclusiv), daca e perioada de proba, datele de facturare si platile prin Netopia
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS plan character varying(20);
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS plan_until date;
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS plan_trial boolean;
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS billing_name character varying(200);
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS billing_cui character varying(30);
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS billing_address character varying(200);
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS billing_city character varying(80);
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS billing_county character varying(80);

CREATE TABLE payments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    order_id character varying(40) NOT NULL,
    plan character varying(20) NOT NULL,
    sms_plan integer NOT NULL,
    months integer NOT NULL,
    amount numeric(10, 2) NOT NULL,
    status character varying(20) NOT NULL,
    ntp_id character varying(80),
    created_at timestamp(6) without time zone NOT NULL,
    paid_at timestamp(6) without time zone,
    plan_until date,
    invoice_number character varying(60),
    invoice_link character varying(500),
    invoice_error character varying(300),
    CONSTRAINT uk_payments_order UNIQUE (order_id)
);
CREATE INDEX idx_payments_user ON payments (user_id, created_at);
