-- Confirmarea emailului la inscriere, resetarea parolei prin email si anunturile despre expirarea abonamentului
-- email_verified null = cont facut inainte (considerat confirmat)
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS email_verified boolean;
-- Ultimul anunt trimis despre expirare ("2026-10-20:SOON" / "2026-10-20:EXPIRED"), ca sa nu plece de doua ori
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS plan_notice character varying(40);

-- Linkuri trimise pe email: se pastreaza doar hash-ul (SHA-256), sunt valabile o perioada si se folosesc o data
CREATE TABLE auth_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    purpose character varying(20) NOT NULL,
    token_hash character varying(64) NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    used_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT uk_auth_tokens_hash UNIQUE (token_hash)
);
CREATE INDEX idx_auth_tokens_user ON auth_tokens (user_id, purpose);
