-- Schema de baza (generata din entitatile JPA cu ddl-auto=update, pg_dump --schema-only).
-- Pe bazele existente (productie) Flyway o sare: baseline-version=1. Pe o baza goala se ruleaza integral.
-- CHECK-urile Hibernate pentru enum-uri sunt scoase intentionat (blocheaza valorile noi; enum-ul e validat in Java).

CREATE TABLE public.app_users (
    id bigint NOT NULL,
    active boolean,
    address character varying(255),
    booking_capacity integer,
    booking_close time(6) without time zone,
    booking_days character varying(20),
    booking_durations character varying(200),
    booking_enabled boolean,
    booking_open time(6) without time zone,
    booking_slug character varying(60),
    callmebot_api_key character varying(100),
    created_at timestamp(6) without time zone,
    digest_channel character varying(20),
    digest_enabled boolean,
    email character varying(255) NOT NULL,
    fleet_id bigint,
    last_digest_date date,
    last_login_at timestamp(6) without time zone,
    password character varying(255) NOT NULL,
    phone character varying(255),
    reminder_template text,
    role character varying(255) NOT NULL,
    station_name character varying(255),
    token_version integer,
    whatsapp_phone character varying(30)
);

ALTER TABLE public.app_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.appointments (
    id bigint NOT NULL,
    appointment_date timestamp(6) without time zone NOT NULL,
    client_name character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    duration_minutes integer,
    itp_record_id bigint,
    license_plate character varying(255),
    phone character varying(255),
    source character varying(20),
    status character varying(255) NOT NULL,
    vehicle_category character varying(20),
    user_id bigint NOT NULL
);

ALTER TABLE public.appointments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.appointments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.car_make (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);

ALTER TABLE public.car_make ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.car_make_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.car_model (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    make_id bigint NOT NULL
);

ALTER TABLE public.car_model ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.car_model_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.clients (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    phone character varying(255),
    user_id bigint
);

ALTER TABLE public.clients ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clients_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.fleet_plates (
    fleet_id bigint NOT NULL,
    plate character varying(20)
);

CREATE TABLE public.fleets (
    id bigint NOT NULL,
    contact_name character varying(120),
    contact_phone character varying(40),
    created_at timestamp(6) without time zone,
    cui character varying(20),
    name character varying(120) NOT NULL,
    user_id bigint NOT NULL
);

ALTER TABLE public.fleets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fleets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.itp_records (
    id bigint NOT NULL,
    inspector character varying(80),
    mileage integer,
    next_itp_date date NOT NULL,
    observations text,
    price double precision,
    reminder_at timestamp(6) without time zone,
    reminder_status character varying(20),
    status character varying(20),
    test_date date NOT NULL,
    validity_months integer NOT NULL,
    vehicle_id bigint NOT NULL
);

ALTER TABLE public.itp_records ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.itp_records_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.managers (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL
);

ALTER TABLE public.managers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.managers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.station_inspectors (
    user_id bigint NOT NULL,
    name character varying(80),
    "position" integer NOT NULL
);

CREATE TABLE public.vehicles (
    id bigint NOT NULL,
    brand character varying(255) NOT NULL,
    license_plate character varying(255) NOT NULL,
    model character varying(255),
    vin character varying(255),
    year integer,
    client_id bigint NOT NULL
);

ALTER TABLE public.vehicles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vehicles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.app_users
    ADD CONSTRAINT app_users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.appointments
    ADD CONSTRAINT appointments_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.car_make
    ADD CONSTRAINT car_make_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.car_model
    ADD CONSTRAINT car_model_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT clients_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.fleets
    ADD CONSTRAINT fleets_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.itp_records
    ADD CONSTRAINT itp_records_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.managers
    ADD CONSTRAINT managers_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.station_inspectors
    ADD CONSTRAINT station_inspectors_pkey PRIMARY KEY (user_id, "position");

ALTER TABLE ONLY public.app_users
    ADD CONSTRAINT uk4vj92ux8a2eehds1mdvmks473 UNIQUE (email);

ALTER TABLE ONLY public.managers
    ADD CONSTRAINT uk9t1pttj95csyjl4it8lxgl7jj UNIQUE (email);

ALTER TABLE ONLY public.car_model
    ADD CONSTRAINT ukhri9khpeots920cvvuh8u2gn3 UNIQUE (make_id, name);

ALTER TABLE ONLY public.car_make
    ADD CONSTRAINT ukpqkhm83twhfqjtdw1nje2goh9 UNIQUE (name);

ALTER TABLE ONLY public.app_users
    ADD CONSTRAINT ukqdk0w519i9843js42y8os1s37 UNIQUE (booking_slug);

ALTER TABLE ONLY public.vehicles
    ADD CONSTRAINT vehicles_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.fleets
    ADD CONSTRAINT fk4hwciltbxlpwoy8kb556iihbt FOREIGN KEY (user_id) REFERENCES public.app_users(id);

ALTER TABLE ONLY public.fleet_plates
    ADD CONSTRAINT fkdagarf2p01nhf4b81t2b5xhng FOREIGN KEY (fleet_id) REFERENCES public.fleets(id);

ALTER TABLE ONLY public.itp_records
    ADD CONSTRAINT fkienux7347ge75if44jcuafvpw FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id);

ALTER TABLE ONLY public.station_inspectors
    ADD CONSTRAINT fkkg45jvibnf5qf9o9nycf2fqf6 FOREIGN KEY (user_id) REFERENCES public.app_users(id);

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT fknkff3j7ntcii1kc56uqawjjvb FOREIGN KEY (user_id) REFERENCES public.app_users(id);

ALTER TABLE ONLY public.vehicles
    ADD CONSTRAINT fkoxy6oykc3j2b4qag4x9pfkmcg FOREIGN KEY (client_id) REFERENCES public.clients(id);

ALTER TABLE ONLY public.appointments
    ADD CONSTRAINT fkp2oiy87e3tejlnbpytw9u0avi FOREIGN KEY (user_id) REFERENCES public.app_users(id);

ALTER TABLE ONLY public.car_model
    ADD CONSTRAINT fkqbmg7588angr3y4m9f3xq4fu FOREIGN KEY (make_id) REFERENCES public.car_make(id);
