-- Cereri de retragere din contract trimise prin functia de retragere de pe site (OUG 34/2014 art. 11^1):
-- cine, ce contract, cand; clientul primeste confirmarea pe email, adminul o vede si o marcheaza rezolvata
CREATE TABLE withdrawals (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(150) NOT NULL,
    email character varying(150) NOT NULL,
    contract character varying(300) NOT NULL,
    message character varying(1000),
    user_id bigint,
    created_at timestamp(6) without time zone NOT NULL,
    handled boolean NOT NULL
);
CREATE INDEX idx_withdrawals_created ON withdrawals (created_at);
