-- Inspectorii devin o echipa: telefon, culoare in calendar, linia pe care lucreaza de obicei, activ / inactiv.
-- ITP-urile pastreaza numele inspectorului (asa apare pe fisa si in istoric); programarile au inspectorul lor.
CREATE TABLE inspectors (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES app_users (id),
    name character varying(80) NOT NULL,
    phone character varying(20),
    color character varying(20),
    active boolean NOT NULL,
    default_line integer,
    position integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL
);
CREATE INDEX idx_inspectors_user ON inspectors (user_id);

INSERT INTO inspectors (user_id, name, active, position, created_at)
SELECT user_id, name, true, position, now() FROM station_inspectors;

DROP TABLE station_inspectors;

-- Cine lucreaza pe ce linie intr-o anumita zi (peste linia implicita a inspectorului); inspector_id null = nimeni
CREATE TABLE line_shifts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES app_users (id),
    shift_date date NOT NULL,
    line_no integer NOT NULL,
    inspector_id bigint REFERENCES inspectors (id) ON DELETE SET NULL,
    CONSTRAINT uk_line_shifts_day_line UNIQUE (user_id, shift_date, line_no)
);

-- Inspectorul ales anume pentru o programare (null = cel de pe linia programarii)
ALTER TABLE appointments ADD COLUMN IF NOT EXISTS inspector_id bigint REFERENCES inspectors (id) ON DELETE SET NULL;
