-- Zilele in care un inspector lipseste (concediu, medical, zi libera), cate un rand pe zi: o perioada = mai multe
-- randuri, ca o zi din mijloc sa se poata scoate usor. In zilele astea nu e pus automat pe nicio linie.
CREATE TABLE inspector_leaves (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES app_users (id),
    inspector_id bigint NOT NULL REFERENCES inspectors (id) ON DELETE CASCADE,
    leave_date date NOT NULL,
    kind character varying(20) NOT NULL,
    note character varying(200),
    CONSTRAINT uk_inspector_leaves_day UNIQUE (inspector_id, leave_date)
);
CREATE INDEX idx_inspector_leaves_user_date ON inspector_leaves (user_id, leave_date);
