-- Emailul optional al clientului la programare (confirmare cu link de calendar)
ALTER TABLE appointments ADD COLUMN IF NOT EXISTS email character varying(150);
-- Managerul primeste email la fiecare programare online (null = da)
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS booking_email_notify boolean;

-- Notificarile din aplicatie ale statiei (programari noi online, anulate / mutate de client, ITP-uri facute de inspectori)
CREATE TABLE notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES app_users (id),
    kind character varying(30) NOT NULL,
    title character varying(200) NOT NULL,
    body character varying(500),
    link character varying(300),
    created_at timestamp(6) without time zone NOT NULL,
    read_at timestamp(6) without time zone
);
CREATE INDEX idx_notifications_user_created ON notifications (user_id, created_at);
