-- Programul online: pauza zilnica (fara programari intre start si end), inchis de sarbatorile legale (null = da)
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS booking_break_start time(6) without time zone;
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS booking_break_end time(6) without time zone;
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS booking_holidays_closed boolean;
-- Tariful ITP per tip de vehicul ("CAR:180,VAN:220", vezi InspectionPrices) si daca apare pe pagina de programare (null = nu)
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS booking_prices character varying(200);
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS booking_show_prices boolean;

-- Zilele in care statia e inchisa (pe langa sarbatorile legale), cate un rand pe zi; nu se pot face programari online
CREATE TABLE station_closed_days (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES app_users (id),
    closed_date date NOT NULL,
    note character varying(100),
    CONSTRAINT uk_station_closed_days_day UNIQUE (user_id, closed_date)
);
