-- Notificarile push (Web Push): cate un rand pentru fiecare browser / telefon pe care un cont (manager sau inspector)
-- a pornit notificarile. token_version = versiunea sesiunilor contului la abonare: dupa schimbarea parolei
-- (revokeTokens) abonamentele vechi nu mai primesc nimic si se sterg la prima trimitere.
CREATE TABLE push_subscriptions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES app_users (id) ON DELETE CASCADE,
    endpoint character varying(1000) NOT NULL,
    p256dh character varying(200) NOT NULL,
    auth character varying(100) NOT NULL,
    token_version integer NOT NULL,
    user_agent character varying(200),
    created_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT uk_push_subscriptions_endpoint UNIQUE (endpoint)
);
CREATE INDEX idx_push_subscriptions_user ON push_subscriptions (user_id);
