-- Istoricul modificarilor unei statii: cine, ce si cand a adaugat, schimbat sau sters.
-- `snapshot` pastreaza datele sterse (JSON), ca stergerea sa poata fi anulata.
CREATE TABLE audit_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES app_users (id),
    actor character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    action character varying(20) NOT NULL,
    entity_type character varying(20) NOT NULL,
    entity_id bigint,
    summary character varying(300) NOT NULL,
    changes text,
    snapshot text,
    restored_at timestamp(6) without time zone
);
CREATE INDEX idx_audit_events_user_created ON audit_events (user_id, created_at);
