-- Remindere SMS automate: setarile statiei si jurnalul trimiterilor.
-- Canal: SMS_GATE = telefonul statiei prin aplicatia "SMS Gateway for Android" (cloud), SMSLINK = gateway SMSLink.ro.
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS auto_sms_enabled boolean;
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS auto_sms_provider character varying(20);
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS auto_sms_days character varying(20);
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS auto_sms_template text;
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS sms_gate_url character varying(200);
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS sms_gate_username character varying(100);
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS sms_gate_password character varying(200);
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS smslink_connection_id character varying(100);
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS smslink_password character varying(200);

-- Un SMS pe ITP si pe treapta (ex. 30 / 7 zile inainte); FAILED se reincearca de cateva ori in zilele urmatoare
CREATE TABLE reminder_sends (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    itp_record_id bigint NOT NULL,
    stage integer NOT NULL,
    phone character varying(30),
    provider character varying(20),
    status character varying(20) NOT NULL,
    attempts integer NOT NULL,
    message_id character varying(100),
    error character varying(300),
    sent_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT uk_reminder_sends_record_stage UNIQUE (itp_record_id, stage)
);
CREATE INDEX idx_reminder_sends_user_sent ON reminder_sends (user_id, sent_at);
