-- Cererile de demonstratie trimise din pagina de prezentare (landing page)
CREATE TABLE leads (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(100) NOT NULL,
    station character varying(150),
    city character varying(80),
    phone character varying(30),
    email character varying(150),
    message character varying(1000),
    created_at timestamp(6) without time zone NOT NULL,
    handled boolean NOT NULL
);
CREATE INDEX idx_leads_created ON leads (created_at);
